version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: home-automation-mqtt-broker
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - home-automation

networks:
  home-automation:
    driver: bridge
